page_cache: fix unused parameter build error
To fix a build error introduced by commit 8fac813("Made live_acqs_
merely be a size_t"):

  src/buffer_cache/alt/page_cache.cc:850:6: error: unused parameter ‘acq’ [-Werror=unused-parameter]
  cc1plus: all warnings being treated as errors
  make[1]: *** [build/release/obj/buffer_cache/alt/page_cache.o] Error 1

Signed-off-by: Liu Aleaxander <Aleaxander@gmail.com>