Change 0xFFFFFFFFFFFFFFFF to a long since that's what .resize() expects.
CC rdb_protocol/protocol.cc -o ../build/release/obj/rdb_protocol/protocol.o

In file included from ./serializer/log/data_block_manager.hpp:8,
                 from ./serializer/log/log_serializer.hpp:17,
                 from ./serializer/config.hpp:6,
                 from rdb_protocol/protocol.cc:22:
./containers/bitset.hpp:81: error: integer constant is too large for ‘long’ type
make: *** [../build/release/obj/rdb_protocol/protocol.o] Error 1